### PR TITLE
Add Code Linter To ‘utopia-php/cli

### PR DESCRIPTION
**Pull request by vasucp1207**
PR related to this [issue](https://github.com/appwrite/appwrite/issues/4364).

### CODE REVIEW

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
@vasucp1207 Great PR! 🤯 Looks like there are issues detected by pint. Please fix the issues so that the GitHub action will pass:

```
gitpod /workspace/cli (linter) $ docker run --rm --interactive --tty   --volume $PWD:/app   composer lint
> ./vendor/bin/pint --test

  ⨯⨯⨯⨯⨯⨯⨯

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Laravel  
    FAIL   ............................................................................................................ 7 files, 7 style issues  
  ⨯ src/CLI/CLI.php braces, curly_braces_position, concat_space, single_quote, Laravel/laravel_phpdoc_order, Laravel/laravel_phpdoc_separation…  
  ⨯ src/CLI/Console.php no_unneeded_control_parentheses, concat_space, single_quote, whitespace_after_comma_in_array, not_operator_with_succes…  
  ⨯ src/CLI/Task.php class_attributes_separation, braces, curly_braces_position, Laravel/laravel_phpdoc_separation, no_unused_imports, Laravel…  
  ⨯ tests/CLI/CLITest.php                                    braces, function_declaration, curly_braces_position, concat_space, ordered_imports  
  ⨯ tests/CLI/ConsoleTest.php                                                                                     concat_space, ordered_imports  
  ⨯ tests/CLI/TaskTest.php                               braces, curly_braces_position, multiline_whitespace_before_semicolons, ordered_imports  
  ⨯ tests/resources/loop.php                                                                        braces, curly_braces_position, concat_space  

Script ./vendor/bin/pint --test handling the lint event returned with error code 1
```

**Comment by vasucp1207** [comment]
- @stnguyen90, check now.


Screenshot 2022-10-27 at 12 14 44 AM

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Review by stnguyen90 — APPROVED** [review]

**Comment by christyjacob4** [comment]
@vasucp1207 The tests are failing. Please run and fix all the linter issues and update the PR

**Comment by vasucp1207** [comment]
@christyjacob4, I think the tests are failing due to the linter check.
I also check the adding code linter PR's in other repos their tests are also failing.

**Comment by stnguyen90** [comment]
@christyjacob4, it looks like travis is using `phpcs` and fails because the styling conflicts with pint.

> The command "vendor/bin/phpcs -p" exited with 2.

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
